- name: Vars perefence
  hosts: local
  connection: local
  vars:
    - NAME: "Vars from play"
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: NAME
  tasks:
    - name: print name
      vars:
        - NAME: Vars from Task
      ansible.builtin.debug:
        msg: "{{ NAME }}"
# Variable perferennce :
# ========================

# 1 Args
# 2 Task

