- name: Error Handling
  hosts: local
  connection: local
  tasks:
    - name: Check user add or not
      ansible.builtin.command: id roboshop
      register: result
      ignore_erros: true

    - name: print result
      ansible.builtin.debug:
        msg: "{{ result}}"
