- name: Task variables
  hosts: local
  connetion: local
  vars:
    COURSE: "DevOps and AWS"
    TRAINER: "Nagababu"
  tasks:
    - name: Task variables in details
      vars:
        TRAINER: " Teja"
      ansible.builtin.debug:
        msg: " COURSE is {{ COURSE }}, TRAINER is {{ TRAINER }}"
